# Generated by Django 3.0.1 on 2019-12-29 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation', models.BooleanField()),
                ('garbage_volume', models.IntegerField()),
                ('lastextraction', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='garbage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_rate', models.IntegerField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_status.status')),
            ],
        ),
    ]
