# Generated by Django 3.0.1 on 2020-01-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='distance',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='location',
            field=models.CharField(default='foobar', max_length=200),
        ),
        migrations.AddField(
            model_name='status',
            name='volume_rate',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='garbage_volume',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.DeleteModel(
            name='garbage',
        ),
    ]
